name: logger_service
description: A log service that wraps an implementation to provide a common interface
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: 
    git: 
      url: https://github.com/leisim/logger
      ref: 623a04e5823d5811aedcca5732dd8ccc60246147

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
