name: logger_service
description: A log service that wraps an implementation to provide a common interface
version: 1.0.2
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
